### ISSUE TITLE
Update the branch policies

### ISSUE THREAD

**Issue by toddysm** [notaryproject/meeting-notes#13]
After reviewing the branch policies for the repository, it seems that the main and release branches can benefit with more strict push and PR review policies. I would like to propose updating those as follows:
Note: @SteveLasker changed to checkboxes to indicate which are completed
Use the following rules for main branche:
- [x] Require PR before merging
- [x] Require 2 approvals
- [x] Dismiss stale PR approvals when new commits are pushed
- [x] Require review from Code Owners
- [x] Require status checks to pass before merging
- [ ] Require conversation resolution before merging
- [x] Require signed commits
- [x] Do not allow bypass the above settings
Please add your comments and proposals for additional changes to this issue.

**Comment by yizha1** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by SteveLasker** [comment]
I noticed most of these were complete, with a few (like the number of reviews) were incomplete.
The above checklist now reflects the current status.

**Comment by vaninrao10** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by priteshbandi** [comment]
LGTM but IANAM

**Comment by patrickzheng200** [comment]
LGTM but IANAM

**Comment by yizha1** [comment]
@toddysm  it seems the policies are not completely applied to this repo. Could you take a look since I don't have the permission to do it.

**Comment by toddysm** [comment]
The `main` branch in this repo had no policies enabled at all. I enabled the above and closing the issue
